name: Fan Ren Xiu Xian Zhuan（A）

on:
  push:
    branches:
      - main

# on:
#   schedule:
#     - cron: "*/13 * * * *"

env:
  DOTNET_VERSION: "9.0" # The .NET SDK version to use
  PROJECT: "padmp4"
  OUTPUT: "/home/runner/out"

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Shanghai"

      - uses: actions/checkout@v4

      - name: Install DotNet
        run: |
          export DOTNET_ROOT=$HOME/.dotnet
          export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools
          # sudo apt-get update
          # sudo apt-get install -y wget
          wget https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh
          chmod +x ./dotnet-install.sh
          ./dotnet-install.sh --channel ${{ env.DOTNET_VERSION }}

      - name: DotNet Info
        run: cd ${{ env.PROJECT }} && $HOME/.dotnet/dotnet --info

      - name: Install dependencies
        run: |
          cd ${{ env.PROJECT }}
          $HOME/.dotnet/dotnet restore

      - name: Build
        run: |
          cd ${{ env.PROJECT }}
          $HOME/.dotnet/dotnet publish -c Release --no-restore -o ${{ env.OUTPUT }} ./${{ env.PROJECT }}.csproj

      - name: Run
        env: # Or as an environment variable
          URL: ${{ vars.A_URL }}
          NAME: ${{ vars.A_NAME }}
          DOWNLOAD_TAGS: ${{ vars.A_DOWNLOAD_TAGS }}
        run: |
          cd ${{ env.OUTPUT }}
          $HOME/.dotnet/dotnet ${{ env.PROJECT }}.dll
          ls -l

      # - name: Archive code coverage results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ vars.A_NAME }}.xml
      #     path: ${{ env.OUTPUT }}/${{ vars.A_NAME }}.xml

      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     name: ${{ vars.A_NAME }}
      #     tag_name: ${{ vars.A_NAME }}
      #     files: ${{ env.OUTPUT }}/${{ vars.A_NAME }}.xml

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true
          artifacts: ${{ env.OUTPUT }}/${{ vars.A_NAME }}.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ vars.A_NAME }}
